/**
 * PROXY_AUTH_TOKEN recovery from `.uap/proxy.env`.
 *
 * Regression cover for the uap-router MCP 401: agent clients spawn UAP as a
 * child process without sourcing `.uap/proxy.env`, so PROXY_AUTH_TOKEN was
 * absent from process.env, no Authorization header was sent, and every call to
 * the local proxy came back 401.
 *
 * The lookup caches at module scope (it is on the per-request path), so each
 * case resets the module registry and re-imports to get a clean cache.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const LOCAL = new URL('http://127.0.0.1:4000/v1/chat/completions');
const REMOTE = new URL('https://api.example.com/v1/chat/completions');

let root: string;
let cwdSpy: ReturnType<typeof vi.spyOn> | undefined;
const savedToken = process.env.PROXY_AUTH_TOKEN;
const savedXdg = process.env.XDG_CONFIG_HOME;

/** Re-import with a cold module cache so the memoised lookup runs again. */
async function freshResolve() {
  vi.resetModules();
  const mod = await import('../../src/models/openai-compat-client.js');
  return mod.resolveRequestCredential;
}

function writeProxyEnv(dir: string, body: string) {
  mkdirSync(join(dir, '.uap'), { recursive: true });
  writeFileSync(join(dir, '.uap', 'proxy.env'), body);
}

describe('PROXY_AUTH_TOKEN from .uap/proxy.env', () => {
  beforeEach(() => {
    root = join(tmpdir(), `uap-proxytoken-${Date.now()}-${Math.random().toString(36).slice(2)}`);
    mkdirSync(root, { recursive: true });
    delete process.env.PROXY_AUTH_TOKEN;
    // Point XDG at an empty dir by default: without this the developer's real
    // ~/.config/uap/proxy.env would satisfy lookups meant to find nothing.
    process.env.XDG_CONFIG_HOME = join(root, 'empty-xdg');
  });

  afterEach(() => {
    cwdSpy?.mockRestore();
    cwdSpy = undefined;
    try { rmSync(root, { recursive: true, force: true }); } catch { /* best effort */ }
    if (savedToken === undefined) delete process.env.PROXY_AUTH_TOKEN;
    else process.env.PROXY_AUTH_TOKEN = savedToken;
    if (savedXdg === undefined) delete process.env.XDG_CONFIG_HOME;
    else process.env.XDG_CONFIG_HOME = savedXdg;
  });

  it('recovers the token from the file when the env var is absent', async () => {
    writeProxyEnv(root, '# generated by uap setup\nPROXY_AUTH_TOKEN=tok-from-file\nPROXY_HOST=0.0.0.0\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-from-file');
  });

  it('finds the file from a nested cwd, since MCP servers launch in subdirectories', async () => {
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=tok-nested\n');
    const nested = join(root, 'packages', 'app', 'src');
    mkdirSync(nested, { recursive: true });
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(nested);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-nested');
  });

  it('never sends a file-sourced token to a non-local endpoint', async () => {
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=tok-secret\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);

    const resolve = await freshResolve();
    expect(resolve({}, REMOTE)).toBeUndefined();
  });

  it('prefers the environment variable over the file', async () => {
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=tok-from-file\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);
    process.env.PROXY_AUTH_TOKEN = 'tok-from-env';

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-from-env');
  });

  it('keeps walking past a proxy.env that has no token in it', async () => {
    // The deliver 401. `uap setup` writes a .uap/proxy.env into EVERY project,
    // but only the install that generated the secret carries the token. Stopping
    // at the first file found meant an agent working in any other project sent
    // an unauthenticated request even though the token was reachable one level up.
    const nested = join(root, 'sub');
    mkdirSync(nested, { recursive: true });
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=tok-outer\n');
    writeProxyEnv(nested, '# generated by uap setup\nPROXY_RECIPE=fusion\n'); // no token
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(nested);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-outer');
  });

  it('falls back to the user-level config when no project file has the token', async () => {
    const fakeHome = join(root, 'home');
    mkdirSync(join(fakeHome, '.config', 'uap'), { recursive: true });
    writeFileSync(join(fakeHome, '.config', 'uap', 'proxy.env'), 'PROXY_AUTH_TOKEN=tok-user\n');
    // A project that has a proxy.env but no token — the real-world shape.
    writeProxyEnv(root, 'PROXY_RECIPE=fusion\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);
    process.env.XDG_CONFIG_HOME = join(fakeHome, '.config');

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-user');
  });

  it('prefers a project token over the user-level one', async () => {
    const fakeHome = join(root, 'home');
    mkdirSync(join(fakeHome, '.config', 'uap'), { recursive: true });
    writeFileSync(join(fakeHome, '.config', 'uap', 'proxy.env'), 'PROXY_AUTH_TOKEN=tok-user\n');
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=tok-project\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);
    process.env.XDG_CONFIG_HOME = join(fakeHome, '.config');

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-project');
  });

  it('returns undefined when no proxy.env exists anywhere above cwd', async () => {
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBeUndefined();
  });

  it('ignores comments and strips wrapping quotes', async () => {
    writeProxyEnv(root, '#PROXY_AUTH_TOKEN=commented-out\nPROXY_AUTH_TOKEN="tok-quoted"\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('tok-quoted');
  });

  it('keeps a token containing = intact (systemd takes the rest of the line)', async () => {
    writeProxyEnv(root, 'PROXY_AUTH_TOKEN=abc=def==\n');
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(root);

    const resolve = await freshResolve();
    expect(resolve({}, LOCAL)).toBe('abc=def==');
  });
});
