#!/usr/bin/env python3
"""
Extract coding patterns from CLAUDE.md and index them into Qdrant.

Creates/updates the 'agent_patterns' collection with embeddings from
all-MiniLM-L6-v2 for on-demand retrieval by the Pattern RAG system.

Generated by: uam patterns generate
"""

import re
import sys
import hashlib
from pathlib import Path
from datetime import datetime, timezone

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

SOURCE_FILE = Path(__file__).resolve().parents[2] / "CLAUDE.md"
QDRANT_HOST = "localhost"
QDRANT_PORT = 6333
COLLECTION_NAME = "agent_patterns"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
VECTOR_SIZE = 384


def extract_patterns(text: str) -> list[dict]:
    patterns = []
    pattern_regex = re.compile(
        r"### Pattern (\d+): (.+?)(?:\s*\((\w+)\))?\n(.*?)(?=\n### Pattern \d+:|\n## |\n---|\Z)",
        re.DOTALL,
    )
    for match in pattern_regex.finditer(text):
        number = int(match.group(1))
        title = match.group(2).strip()
        abbreviation = match.group(3) or ""
        body = match.group(4).strip()
        detection = ""
        det_match = re.search(r"\*\*Detection\*\*:\s*(.+?)(?:\n\n|\n\*\*)", body, re.DOTALL)
        if det_match:
            detection = det_match.group(1).strip()
        if number <= 11:
            category = "universal"
        elif number <= 20:
            category = "execution"
        elif number <= 26:
            category = "domain-specific"
        elif number <= 31:
            category = "verification"
        else:
            category = "advanced-execution"
        keywords = set(title.lower().split())
        if abbreviation:
            keywords.add(abbreviation.lower())
        if len(body) > 2000:
            body = body[:2000] + "\n... (truncated)"
        patterns.append({
            "id": number, "title": title, "abbreviation": abbreviation,
            "category": category, "detection": detection,
            "keywords": list(keywords), "body": body,
            "content_hash": hashlib.md5(body.encode()).hexdigest(),
        })
    return patterns


def index_to_qdrant(patterns: list[dict]) -> None:
    client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
    model = SentenceTransformer(EMBEDDING_MODEL)
    collections = [c.name for c in client.get_collections().collections]
    if COLLECTION_NAME in collections:
        client.delete_collection(COLLECTION_NAME)
        print(f"  Deleted existing '{COLLECTION_NAME}' collection")
    client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE),
    )
    print(f"  Created '{COLLECTION_NAME}' collection ({VECTOR_SIZE}-dim cosine)")
    points = []
    for p in patterns:
        embed_text = f"{p['title']}. {p['abbreviation']}. {p['detection']}. {p['body'][:500]}"
        vector = model.encode(embed_text).tolist()
        points.append(PointStruct(
            id=p["id"], vector=vector,
            payload={
                "title": p["title"], "abbreviation": p["abbreviation"],
                "category": p["category"], "detection": p["detection"],
                "keywords": p["keywords"], "body": p["body"],
                "content_hash": p["content_hash"],
                "indexed_at": datetime.now(tz=timezone.utc).isoformat(),
            },
        ))
    client.upsert(collection_name=COLLECTION_NAME, points=points)
    print(f"  Indexed {len(points)} patterns")


def main():
    print("=== UAM Pattern Indexer ===")
    if not SOURCE_FILE.exists():
        print(f"ERROR: {SOURCE_FILE} not found")
        sys.exit(1)
    text = SOURCE_FILE.read_text()
    print(f"  Read {SOURCE_FILE.name} ({len(text)} bytes)")
    patterns = extract_patterns(text)
    print(f"  Extracted {len(patterns)} patterns")
    index_to_qdrant(patterns)
    print(f"\nTotal: {len(patterns)} documents in '{COLLECTION_NAME}' collection")


if __name__ == "__main__":
    main()
