#!/usr/bin/env python3
"""
Extract knowledge from project documentation and index into Qdrant.

Scans multiple sources:
  1. CLAUDE.md (with @include resolution)
  2. AGENTS.md and other configured source files
  3. .claude/skills/*/SKILL.md (skill files)

Creates/updates the 'agent_patterns' collection with embeddings from
all-MiniLM-L6-v2 for on-demand retrieval by the Pattern RAG system.

Generated by: uap patterns generate (v0.8.1+)
"""

import re
import sys
import hashlib
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PRIMARY_SOURCE = PROJECT_ROOT / "CLAUDE.md"
ADDITIONAL_SOURCES = []
SKILLS_DIR: Optional[str] = None
QDRANT_HOST = "localhost"
QDRANT_PORT = 6333
COLLECTION_NAME = "agent_patterns"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
VECTOR_SIZE = 384
MAX_BODY_CHARS = 2000


def resolve_includes(text: str, base_dir: Path) -> str:
    """Resolve @include directives (e.g. @hooks-session-start.md)."""

    def replace_include(match):
        filename = match.group(1).strip()
        # Search common locations
        candidates = [
            base_dir / filename,
            base_dir / ".claude" / "hooks" / filename,
            base_dir / ".claude" / filename,
            base_dir / "docs" / filename,
        ]
        for candidate in candidates:
            if candidate.exists():
                return candidate.read_text()
        return match.group(0)  # Keep original if not found

    return re.sub(r"^@(\S+\.md)$", replace_include, text, flags=re.MULTILINE)


def extract_numbered_patterns(text: str) -> list[dict]:
    """Extract '### Pattern N: Title' blocks (legacy format)."""
    patterns = []
    pattern_regex = re.compile(
        r"### Pattern (\d+): (.+?)(?:\s*\((\w+)\))?\n(.*?)(?=\n### Pattern \d+:|\n## |\n---|\Z)",
        re.DOTALL,
    )
    for match in pattern_regex.finditer(text):
        number = int(match.group(1))
        title = match.group(2).strip()
        abbreviation = match.group(3) or ""
        body = match.group(4).strip()
        if len(body) > MAX_BODY_CHARS:
            body = body[:MAX_BODY_CHARS] + "\n... (truncated)"
        patterns.append(
            {
                "title": title,
                "abbreviation": abbreviation,
                "category": "pattern",
                "source": "CLAUDE.md",
                "keywords": list(set(title.lower().split())),
                "body": body,
                "content_hash": hashlib.md5(body.encode()).hexdigest(),
            }
        )
    return patterns


def extract_sections(text: str, source_name: str) -> list[dict]:
    """Extract ## and ### heading sections from any markdown file."""
    sections = []
    # Split on ## headings (level 2 and 3)
    heading_regex = re.compile(r"^(#{2,3})\s+(.+)$", re.MULTILINE)
    matches = list(heading_regex.finditer(text))

    for i, match in enumerate(matches):
        level = len(match.group(1))
        title = match.group(2).strip()

        # Skip HTML comments, empty titles, very short titles
        if title.startswith("<!--") or len(title) < 3:
            continue

        # Get body until next heading of same or higher level
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end].strip()

        # Skip empty or trivial sections
        if len(body) < 20:
            continue

        if len(body) > MAX_BODY_CHARS:
            body = body[:MAX_BODY_CHARS] + "\n... (truncated)"

        # Classify category from source name and content
        category = classify_section(title, body, source_name)

        # Build keywords from title
        keywords = [w.lower() for w in re.findall(r"[a-zA-Z]{3,}", title)]

        sections.append(
            {
                "title": title,
                "abbreviation": "",
                "category": category,
                "source": source_name,
                "keywords": keywords,
                "body": body,
                "content_hash": hashlib.md5(body.encode()).hexdigest(),
            }
        )

    return sections


def classify_section(title: str, body: str, source: str) -> str:
    """Classify a section into a category based on content signals."""
    t = title.lower()
    b = body.lower()[:500]

    if "skill" in source.lower():
        return "skill"
    if any(w in t for w in ["deploy", "kubernetes", "k8s", "cluster", "infra"]):
        return "infrastructure"
    if any(w in t for w in ["security", "auth", "secret", "owasp", "xss"]):
        return "security"
    if any(w in t for w in ["test", "coverage", "vitest", "jest"]):
        return "testing"
    if any(w in t for w in ["performance", "optimize", "cache", "latency"]):
        return "performance"
    if any(w in t for w in ["workflow", "protocol", "checklist", "process"]):
        return "workflow"
    if any(w in t for w in ["database", "postgres", "sql", "pgdog", "cnpg"]):
        return "database"
    if any(w in t for w in ["observ", "monitor", "metric", "log", "trace"]):
        return "observability"
    if any(w in t for w in ["design", "ui", "ux", "css", "style", "theme"]):
        return "design"
    if any(w in t for w in ["review", "quality", "lint", "code"]):
        return "code-quality"
    if "terraform" in b or "iac" in t:
        return "infrastructure"
    return "general"


def extract_skill_frontmatter(text: str) -> tuple[str, str]:
    """Extract name and description from YAML frontmatter."""
    fm_match = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not fm_match:
        return "", ""
    fm = fm_match.group(1)
    name_match = re.search(r"^name:\s*(.+)$", fm, re.MULTILINE)
    desc_match = re.search(r'^description:\s*["\'"]?(.+?)["\'"]?\s*$', fm, re.MULTILINE)
    name = name_match.group(1).strip().strip('"').strip("'") if name_match else ""
    desc = desc_match.group(1).strip().strip('"').strip("'") if desc_match else ""
    return name, desc


def scan_skills(project_root: Path, skills_dir: Optional[str]) -> list[dict]:
    """Scan .claude/skills/*/SKILL.md files."""
    docs = []
    # Auto-detect skills directory
    candidates = []
    if skills_dir:
        candidates.append(project_root / skills_dir)
    candidates.extend(
        [
            project_root / ".claude" / "skills",
            project_root / ".factory" / "skills",
        ]
    )

    for skills_path in candidates:
        if not skills_path.is_dir():
            continue
        skill_files = sorted(skills_path.glob("*/SKILL.md"))
        for sf in skill_files:
            text = sf.read_text()
            skill_name, skill_desc = extract_skill_frontmatter(text)
            if not skill_name:
                skill_name = sf.parent.name

            # Extract sections from the skill file
            sections = extract_sections(text, f"skill:{skill_name}")

            # If no sections extracted, index the whole skill as one doc
            if not sections and len(text.strip()) > 50:
                body = text.strip()
                if len(body) > MAX_BODY_CHARS:
                    body = body[:MAX_BODY_CHARS] + "\n... (truncated)"
                sections = [
                    {
                        "title": skill_name,
                        "abbreviation": "",
                        "category": "skill",
                        "source": f"skill:{skill_name}",
                        "keywords": [
                            w.lower()
                            for w in re.findall(
                                r"[a-zA-Z]{3,}", skill_name + " " + skill_desc
                            )
                        ],
                        "body": body,
                        "content_hash": hashlib.md5(body.encode()).hexdigest(),
                    }
                ]

            # Add skill description as keywords to all sections
            if skill_desc:
                desc_keywords = [
                    w.lower() for w in re.findall(r"[a-zA-Z]{3,}", skill_desc)
                ]
                for s in sections:
                    s["keywords"] = list(set(s["keywords"] + desc_keywords))

            docs.extend(sections)
        if docs:
            break  # Use first found skills directory

    return docs


def deduplicate(docs: list[dict]) -> list[dict]:
    """Remove duplicate documents by content hash."""
    seen = set()
    unique = []
    for d in docs:
        h = d["content_hash"]
        if h not in seen:
            seen.add(h)
            unique.append(d)
    return unique


def index_to_qdrant(docs: list[dict]) -> None:
    """Create collection and upsert document embeddings."""
    if not docs:
        print("  No documents to index — skipping")
        return

    client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
    model = SentenceTransformer(EMBEDDING_MODEL, device="cpu")

    # Recreate collection
    collections = [c.name for c in client.get_collections().collections]
    if COLLECTION_NAME in collections:
        client.delete_collection(COLLECTION_NAME)
        print(f"  Deleted existing '{COLLECTION_NAME}' collection")

    client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE),
    )
    print(f"  Created '{COLLECTION_NAME}' collection ({VECTOR_SIZE}-dim cosine)")

    # Assign sequential IDs and build embeddings
    points = []
    for idx, doc in enumerate(docs, start=1):
        embed_text = (
            f"{doc['title']}. {' '.join(doc['keywords'][:10])}. {doc['body'][:500]}"
        )
        vector = model.encode(embed_text).tolist()
        points.append(
            PointStruct(
                id=idx,
                vector=vector,
                payload={
                    "title": doc["title"],
                    "abbreviation": doc.get("abbreviation", ""),
                    "category": doc["category"],
                    "source": doc.get("source", ""),
                    "detection": doc.get("detection", ""),
                    "keywords": doc["keywords"],
                    "body": doc["body"],
                    "content_hash": doc["content_hash"],
                    "indexed_at": datetime.now(tz=timezone.utc).isoformat(),
                },
            )
        )

    # Batch upsert (Qdrant handles large batches fine)
    BATCH_SIZE = 100
    for i in range(0, len(points), BATCH_SIZE):
        batch = points[i : i + BATCH_SIZE]
        client.upsert(collection_name=COLLECTION_NAME, points=batch)
    print(f"  Indexed {len(points)} documents")


def main():
    print("=== UAP Pattern Indexer (v2 — multi-source) ===")
    all_docs: list[dict] = []

    # 1. Primary source (CLAUDE.md) with @include resolution
    if PRIMARY_SOURCE.exists():
        text = PRIMARY_SOURCE.read_text()
        text = resolve_includes(text, PROJECT_ROOT)
        print(f"  Read {PRIMARY_SOURCE.name} ({len(text)} bytes, includes resolved)")

        # Try legacy numbered patterns first
        patterns = extract_numbered_patterns(text)
        if patterns:
            print(f"  Extracted {len(patterns)} numbered patterns")
            all_docs.extend(patterns)

        # Also extract heading-based sections
        sections = extract_sections(text, PRIMARY_SOURCE.name)
        if sections:
            print(f"  Extracted {len(sections)} sections from {PRIMARY_SOURCE.name}")
            all_docs.extend(sections)
    else:
        print(f"  {PRIMARY_SOURCE.name} not found — skipping")

    # 2. Additional source files (AGENTS.md, etc.)
    for src_name in ADDITIONAL_SOURCES:
        src_path = PROJECT_ROOT / src_name
        if src_path.exists():
            text = src_path.read_text()
            sections = extract_sections(text, src_name)
            print(f"  Extracted {len(sections)} sections from {src_name}")
            all_docs.extend(sections)
        else:
            print(f"  {src_name} not found — skipping")

    # 3. Auto-detect common files if no additional sources configured
    if not ADDITIONAL_SOURCES:
        for auto_file in ["AGENTS.md", "CONTRIBUTING.md"]:
            auto_path = PROJECT_ROOT / auto_file
            if auto_path.exists():
                text = auto_path.read_text()
                sections = extract_sections(text, auto_file)
                if sections:
                    print(f"  Auto-detected {auto_file}: {len(sections)} sections")
                    all_docs.extend(sections)

    # 4. Scan skill files
    skills = scan_skills(PROJECT_ROOT, SKILLS_DIR)
    if skills:
        print(f"  Scanned skills: {len(skills)} documents")
        all_docs.extend(skills)

    # Deduplicate
    all_docs = deduplicate(all_docs)
    print(f"  Total unique documents: {len(all_docs)}")

    # Index
    index_to_qdrant(all_docs)

    # Summary by category
    categories: dict[str, int] = {}
    for d in all_docs:
        categories[d["category"]] = categories.get(d["category"], 0) + 1
    print("\n=== Summary by Category ===")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat:>20}: {count}")

    print(f"\nTotal: {len(all_docs)} documents in '{COLLECTION_NAME}' collection")


if __name__ == "__main__":
    main()
