#!/usr/bin/env python3
"""
Query the agent_patterns Qdrant collection for task-relevant patterns.

Generated by: uam patterns generate
"""

import argparse
import json
import sys

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient

QDRANT_HOST = "localhost"
QDRANT_PORT = 6333
COLLECTION_NAME = "agent_patterns"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

_model = None


def get_model():
    global _model
    if _model is None:
        _model = SentenceTransformer(EMBEDDING_MODEL)
    return _model


def query_patterns(query: str, top_k: int = 2, min_score: float = 0.35) -> list[dict]:
    client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
    model = get_model()
    vector = model.encode(query).tolist()
    results = client.query_points(
        collection_name=COLLECTION_NAME,
        query=vector,
        limit=top_k,
        score_threshold=min_score,
    )
    patterns = []
    for hit in results.points:
        patterns.append({
            "id": hit.id,
            "score": round(hit.score, 4),
            "title": hit.payload.get("title", ""),
            "abbreviation": hit.payload.get("abbreviation", ""),
            "category": hit.payload.get("category", ""),
            "body": hit.payload.get("body", ""),
        })
    return patterns


def format_for_context(patterns: list[dict]) -> str:
    if not patterns:
        return ""
    lines = ["<uam-patterns>"]
    for p in patterns:
        abbr = f" ({p['abbreviation']})" if p["abbreviation"] else ""
        lines.append(f"### Pattern {p['id']}: {p['title']}{abbr}")
        lines.append(f"Relevance: {p['score']}")
        lines.append(p["body"])
        lines.append("")
    lines.append("</uam-patterns>")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Query UAM pattern collection")
    parser.add_argument("query", help="Task description to match patterns against")
    parser.add_argument("--top", type=int, default=2)
    parser.add_argument("--min-score", type=float, default=0.35)
    parser.add_argument("--format", choices=["text", "json", "context"], default="text")
    args = parser.parse_args()
    try:
        patterns = query_patterns(args.query, top_k=args.top, min_score=args.min_score)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    if args.format == "json":
        print(json.dumps(patterns, indent=2))
    elif args.format == "context":
        print(format_for_context(patterns))
    else:
        if not patterns:
            print("No matching patterns found.")
            return
        for p in patterns:
            abbr = f" ({p['abbreviation']})" if p["abbreviation"] else ""
            print(f"[{p['score']:.3f}] P{p['id']}: {p['title']}{abbr} [{p['category']}]")
            print(f"  {p['body'][:200]}...")
            print()


if __name__ == "__main__":
    main()
