# UAP ForgeCode Integration Plugin
# Auto-generated by: uap hooks install forgecode  
# Add this line to ~/.zshrc after installing UAP: source "$PWD/.forge/forgecode.plugin.sh"

_uap_forgecode_session_start() {
  # Load recent memory context from UAP database before command execution

  local PROJECT_DIR="${FORGE_UAP_PROJECT:-.}"
  local DB_PATH="\$PROJECT_DIR/agents/data/memory/short_term.db"
  local COORD_DB="\$PROJECT_DIR/agents/data/coordination/coordination.db"
  local POLICY_DB="\$PROJECT_DIR/agents/data/memory/policies.db"
  local AGENT_ID="forgecode-\$(date +%s | tail -c 7)"

  if [ ! -f "\$DB_PATH" ]; then return 0; fi

  # Clean stale agents from coordination DB (heartbeat >24h old)
  if [ -f "\$COORD_DB" ] && command -v sqlite3 &> /dev/null; then
    sqlite3 "\$COORD_DB" "
      DELETE FROM work_claims WHERE agent_id IN (
        SELECT id FROM agent_registry
        WHERE status IN ('active','idle') AND last_heartbeat < datetime('now','-24 hours')
      );
      DELETE FROM work_announcements WHERE agent_id IN (
        SELECT id FROM agent_registry
        WHERE status IN ('active','idle') AND last_heartbeat < datetime('now','-24 hours')
      ) AND completed_at IS NULL;
      UPDATE agent_registry SET status='failed'
        WHERE status IN ('active','idle') AND last_heartbeat < datetime('now','-24 hours');
    " 2>/dev/null || true

    # Register this agent
    sqlite3 "\$COORD_DB" "
      INSERT OR REPLACE INTO agent_registry (id, name, session_id, status, capabilities, started_at, last_heartbeat)
      VALUES ('\$AGENT_ID', 'forgecode', '\$AGENT_ID', 'active', '[]', datetime('now'), datetime('now'));
    " 2>/dev/null || true

    # Auto-announce session
    sqlite3 "\$COORD_DB" "
      INSERT INTO work_announcements (agent_id, agent_name, intent_type, resource, description, announced_at)
      VALUES ('\$AGENT_ID', 'forgecode', 'editing', 'session-scope', 'Session \$AGENT_ID active', datetime('now'));
    " 2>/dev/null || true

    # Detect overlaps from other agents
    local OVERLAPS=\$(sqlite3 "\$COORD_DB" "
      SELECT agent_id || ' on ' || resource || ' (' || intent_type || ')'
      FROM work_announcements
      WHERE completed_at IS NULL AND agent_id != '\$AGENT_ID'
      ORDER BY announced_at DESC LIMIT 5;
    " 2>/dev/null || true)

    if [ -n "\$OVERLAPS" ]; then
      echo "[UAP-ForgeCode] OVERLAP DETECTED: \$OVERLAPS" >&2
    fi

    export UAP_AGENT_ID="\$AGENT_ID"
  fi

  # Policy summary
  if [ -f "\$POLICY_DB" ] && command -v sqlite3 &> /dev/null; then
    local ACTIVE_POLICIES=\$(sqlite3 "\$POLICY_DB" "SELECT COUNT(*) FROM policies WHERE isActive=1;" 2>/dev/null || echo 0)
    local REQUIRED_POLICIES=\$(sqlite3 "\$POLICY_DB" "SELECT COUNT(*) FROM policies WHERE isActive=1 AND level='REQUIRED';" 2>/dev/null || echo 0)
    echo "[UAP-ForgeCode] Policies: \$ACTIVE_POLICIES active (\$REQUIRED_POLICIES REQUIRED)" >&2
  fi

  # Inject recent memory context via environment variable for ForgeCode to read
  local MEMORIES=""

  if command -v sqlite3 &> /dev/null; then
    MEMORIES=\$(sqlite3 "\$DB_PATH" "
      SELECT type, substr(content,1,80) FROM memories
      WHERE timestamp >= datetime('now', '-1 day')
      ORDER BY id DESC LIMIT 5;
    " 2>/dev/null || true)

    if [ -n "\$MEMORIES" ]; then
      export UAP_CONTEXT="\$MEMORIES"
      echo "[UAP-ForgeCode] Memory context loaded (\$(echo \"\$MEMORIES\" | wc -l) recent items)" >&2
    fi
  fi

  # Load open loops/high importance decisions from session memories
  local OPEN_LOOPS=""

  if command -v sqlite3 &> /dev/null; then
    OPEN_LOOPS=\$(sqlite3 "\$DB_PATH" "
      SELECT content FROM session_memories
      WHERE type IN ('action','goal','decision') AND importance >= 7
      ORDER BY id DESC LIMIT 5;
    " 2>/dev/null || true)

    if [ -n "\$OPEN_LOOPS" ]; then
      export UAP_OPEN_LOOPS="\$OPEN_LOOPS"
      echo "[UAP-ForgeCode] Open loops: \$(echo \"\$OPEN_LOOPS\" | grep -c .) high-priority items pending" >&2
    fi
  fi

  # Warn about stale worktrees if any exist
  local WORKTREES_DIR="\$PROJECT_DIR/.worktrees"
  if [ -d "\$WORKTREES_DIR" ]; then
    local STALE_COUNT=\$(find "\$WORKTREES_DIR" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l)
    if [ "\$STALE_COUNT" -gt 0 ]; then
      echo "[UAP-ForgeCode] Worktrees: \$STALE_COUNT active (run 'uap worktree list' to review)" >&2
    fi
  fi
}

_uap_forgecode_pre_compact() {
  # Save compaction marker before model switches in ForgeCode session

  local PROJECT_DIR="${FORGE_UAP_PROJECT:-.}"
  local DB_PATH="\$PROJECT_DIR/agents/data/memory/short_term.db"
  local COORD_DB="\$PROJECT_DIR/agents/data/coordination/coordination.db"

  if [ ! -f "\$DB_PATH" ]; then return 0; fi

  local TIMESTAMP=\$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  # Record compaction event in memory database
  sqlite3 "\$DB_PATH" "INSERT OR IGNORE INTO memories (timestamp, type, content) VALUES ('\${TIMESTAMP}', 'action', '[pre-compact] Context saved before model switch');" 2>/dev/null || true

  # Flush pending deploys before session ends
  if [ -f "\$COORD_DB" ] && command -v sqlite3 &> /dev/null; then
    local PENDING=\$(sqlite3 "\$COORD_DB" "SELECT COUNT(*) FROM deploy_queue WHERE status='pending';" 2>/dev/null || echo 0)
    if [ "\$PENDING" -gt 0 ] 2>/dev/null && [ -f "\$PROJECT_DIR/dist/bin/cli.js" ]; then
      echo "[UAP-ForgeCode] Flushing \$PENDING pending deploy actions..." >&2
      node "\$PROJECT_DIR/dist/bin/cli.js" deploy flush 2>/dev/null || true
    fi
  fi

  # Close announcements and deregister agent
  if [ -f "\$COORD_DB" ] && [ -n "\${UAP_AGENT_ID:-}" ]; then
    sqlite3 "\$COORD_DB" "
      UPDATE work_announcements SET completed_at=datetime('now') WHERE agent_id='\$UAP_AGENT_ID' AND completed_at IS NULL;
      UPDATE agent_registry SET status='completed' WHERE id='\$UAP_AGENT_ID';
    " 2>/dev/null || true
  fi

  echo "[UAP-ForgeCode] Pre-compaction marker saved at \$TIMESTAMP" >&2
}

# Auto-register hooks with ForgeCode's : command via environment variables  
_uap_forgecode_register() {
  # Add to ~/.zshrc if not already present (user confirmation required)
  local ZSHRC="\$HOME/.zshrc"
  
  if [ -f "\$ZSHRC" ] && ! grep -q "UAP_FORGE_CODE_PLUGIN" "\$ZSHRC"; then
    echo '# UAP ForgeCode Integration' >> "\$ZSHRC"
    echo 'source "$PWD/.forge/forgecode.plugin.sh"' >> "\$ZSHRC"  
    echo '[UAP-ForgCode] Added plugin source to ~/.zshrc - run "source \$HOME/.zshrc" or restart terminal to activate' >&2
  fi
  
  # Create config file for ForgeCode settings
  local CONFIG_PATH="\$PROJECT_DIR/.forge/settings.local.json"
  
  if [ ! -f "\$CONFIG_PATH" ]; then
    cat > "\$CONFIG_PATH" <<EOF
{
  "uapIntegration": {
    "enabled": true,
    "memoryDbPath": "./agents/data/memory/short_term.db",
    "coordinationDbPath": "./agents/data/coordination/coordination.db",  
    "hooksEnabled": ["sessionStart", "preCompact"]
  },
  "worktrees": {
    "enabled": true,
    "directory": ".worktrees"
  }
}
EOF 
    echo "[UAP-ForgCode] ✅ Created .forge/settings.local.json with UAP integration config" >&2  
  fi
  
  # Add to gitignore if not present
  local GITIGNORE="\$PROJECT_DIR/.gitignore"
  if [ -f "\$GITIGNORE" ] && ! grep -q "settings.local.json" "\$GITIGNORE"; then
    echo "# UAP ForgeCode settings (auto-generated)" >> "\$GITIGNORE"  
    echo ".forge/settings.local.json" >> "\$GITIGNORE"
    echo "[UAP-ForgCode] ✅ Added .forge/ to gitignore for local config files" >&2
  fi
  
  # Auto-activate hooks in current session if running interactively
  _uap_forgecode_session_start &>/dev/null || true  
}

# Export functions so they can be sourced by other scripts
export -f _uap_forgecode_session_start \
           _uap_forgecode_pre_compact \
           _uap_forgecode_register;
