# UAP ForgeCode Integration Plugin
// Auto-generated by: uap hooks install forgecode  
// Add this line to ~/.zshrc after installing UAP: source "$PWD/.forge/forgecode.plugin.sh"

_uap_forgecode_session_start() {
  # Load recent memory context from UAP database before : command execution
  
  local PROJECT_DIR="${FORGE_UAP_PROJECT:-.}"
  
  if [ ! -f "\$PROJECT_DIR/./agents/data/memory/short_term.db" ]; then exit 0; fi

  # Clean stale agents from coordination DB (heartbeat >24h old)
  if [ -f "\$PROJECT_DIR/./agents/data/coordination/coordination.db" ] && command -v sqlite3 &> /dev/null; then
    sqlite3 "\$PROJECT_DIR/./agents/data/coordination/coordination.db" "
      DELETE FROM work_claims WHERE agent_id IN (
        SELECT id FROM agent_registry
        WHERE status IN ('active','idle') AND last_heartbeat < datetime('now','-24 hours');
      );
      UPDATE agent_registry SET status='failed'
        WHERE status IN ('active','idle') AND last_heartbeat < datetime('now','-24 hours');
    " 2>/dev/null || true
  fi

  # Inject recent memory context via environment variable for ForgeCode to read
  local MEMORIES=""
  
  if command -v sqlite3 &> /dev/null; then
    MEMORIES=\$(sqlite3 "\$PROJECT_DIR/./agents/data/memory/short_term.db" "
      SELECT type, substr(content,1,80) FROM memories
      WHERE timestamp >= datetime('now', '-1 day')
      ORDER BY id DESC LIMIT 5;
    " 2>/dev/null || true)
    
    if [ -n "\$MEMORIES" ]; then
      export UAP_CONTEXT="\$MEMORIES"  
      echo "[UAP-ForgCode] ✅ Memory context loaded for session (\$(echo \"\$MEMORIES\" | wc -l)) recent items)" >&2
    fi
  fi
  
  # Load open loops/high importance decisions from session memories
  local OPEN_LOOPS=""
  
  if command -v sqlite3 &> /dev/null; then
    OPEN_LOOPS=\$(sqlite3 "\$PROJECT_DIR/./agents/data/memory/short_term.db" "
      SELECT content FROM session_memories
      WHERE type IN ('action','goal','decision') AND importance >= 7
      ORDER BY id DESC LIMIT 5;
    " 2>/dev/null || true)
    
    if [ -n "\$OPEN_LOOPS" ]; then
      export UAP_OPEN_LOOPS="\$OPEN_LOOPS"  
      echo "[UAP-ForgCode] ℹ️ Open loops detected (\$(echo \"\$OPEN_LOOPS\" | grep -c .)) high-priority items pending" >&2
    fi
  fi
  
  # Warn about stale worktrees if any exist
  local WORKTREES_DIR="\$PROJECT_DIR/.worktrees"  
  if [ -d "\$WORKTREES_DIR" ]; then
    local STALE_COUNT=\$(find "\$WORKTREES_DIR" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l)
    if [ "\$STALE_COUNT" -gt 0 ] && command -v find &> /dev/null; then
      echo "[UAP-ForgCode] ⚠️ Stale worktrees: \$STALE_COUNT (run 'uap worktree list' to cleanup)" >&2
    fi
  fi  
}

_uap_forgecode_pre_compact() {
  # Save compaction marker before model switches in ForgeCode session
  
  local PROJECT_DIR="${FORGE_UAP_PROJECT:-.}"
  
  if [ ! -f "\$PROJECT_DIR/./agents/data/memory/short_term.db" ]; then exit 0; fi

  local TIMESTAMP=\$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  
  # Record compaction event in memory database for session tracking  
  sqlite3 "\$PROJECT_DIR/./agents/data/memory/short_term.db" "INSERT OR IGNORE INTO memories (timestamp, type, content) VALUES ('\${TIMESTAMP}', 'action', '[pre-compact] Context saved before model switch');" 2>/dev/null || true
  
  echo "[UAP-ForgCode] ✅ Pre-compaction marker saved at \$TIMESTAMP" >&2
}

# Auto-register hooks with ForgeCode's : command via environment variables  
_uap_forgecode_register() {
  # Add to ~/.zshrc if not already present (user confirmation required)
  local ZSHRC="\$HOME/.zshrc"
  
  if [ -f "\$ZSHRC" ] && ! grep -q "UAP_FORGE_CODE_PLUGIN" "\$ZSHRC"; then
    echo '# UAP ForgeCode Integration' >> "\$ZSHRC"
    echo 'source "$PWD/.forge/forgecode.plugin.sh"' >> "\$ZSHRC"  
    echo '[UAP-ForgCode] Added plugin source to ~/.zshrc - run "source \$HOME/.zshrc" or restart terminal to activate' >&2
  fi
  
  # Create config file for ForgeCode settings
  local CONFIG_PATH="\$PROJECT_DIR/.forge/settings.local.json"
  
  if [ ! -f "\$CONFIG_PATH" ]; then
    cat > "\$CONFIG_PATH" <<EOF
{
  "uapIntegration": {
    "enabled": true,
    "memoryDbPath": "./agents/data/memory/short_term.db",
    "coordinationDbPath": "./agents/data/coordination/coordination.db",  
    "hooksEnabled": ["sessionStart", "preCompact"]
  },
  "worktrees": {
    "enabled": true,
    "directory": ".worktrees"
  }
}
EOF 
    echo "[UAP-ForgCode] ✅ Created .forge/settings.local.json with UAP integration config" >&2  
  fi
  
  # Add to gitignore if not present
  local GITIGNORE="\$PROJECT_DIR/.gitignore"
  if [ -f "\$GITIGNORE" ] && ! grep -q "settings.local.json" "\$GITIGNORE"; then
    echo "# UAP ForgeCode settings (auto-generated)" >> "\$GITIGNORE"  
    echo ".forge/settings.local.json" >> "\$GITIGNORE"
    echo "[UAP-ForgCode] ✅ Added .forge/ to gitignore for local config files" >&2
  fi
  
  # Auto-activate hooks in current session if running interactively
  _uap_forgecode_session_start &>/dev/null || true  
}

# Export functions so they can be sourced by other scripts
export -f _uap_forgecode_session_start \
           _uap_forgecode_pre_compact \
           _uap_forgecode_register;
