/**
 * Vision Judge — aesthetic/behavioral review of the visual gate's screenshots
 * by a vision-capable model (the seam the visual-verification policy names).
 *
 * The pixel heuristics prove "renders and moves"; only vision can judge
 * "looks right". When UAP_VISION_MODEL (+ UAP_VISION_ENDPOINT, OpenAI-compat
 * with image_url support) is configured, the saved screenshots are scored
 * against the spec; findings flow into reports/acceptance evidence as
 * ADVISORY context. Unset config or any failure returns null — this seam is
 * fail-soft by contract and never blocks a delivery on its own.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { fetchModelWithRetry } from '../models/long-fetch.js';

export interface VisionVerdict {
  /** 0–10 aesthetic/behavioral score across the reviewed screenshots. */
  score: number;
  findings: string[];
}

const MAX_IMAGES = 4;
const MAX_FINDINGS = 8;

export function visionJudgeConfigured(): boolean {
  return Boolean(process.env.UAP_VISION_MODEL && process.env.UAP_VISION_ENDPOINT);
}

/**
 * Auto-configure the vision judge from the ACTIVE local model when it isn't
 * explicitly configured. The aesthetic review used to report "no vision model"
 * whenever UAP_VISION_ENDPOINT/MODEL were unset — even though the local model
 * serving the run (e.g. Qwen3.6 with an mmproj projector) is vision-capable.
 * Probe candidate local OpenAI-compat endpoints' /props for
 * modalities.vision === true and, on a hit, set UAP_VISION_ENDPOINT/MODEL so
 * the judge uses the active model. Fail-soft: any error leaves config unset
 * (the caller then reports "not configured" exactly as before). Idempotent.
 */
export async function autodetectLocalVision(): Promise<boolean> {
  if (visionJudgeConfigured()) return true;
  // Candidate OpenAI-compat bases, most-specific first. LLAMA_CPP_BASE is what
  // the proxy talks to; the rest are conventional local llama-server ports.
  const bases = [
    process.env.UAP_INFERENCE_ENDPOINT,
    process.env.LLAMA_CPP_BASE,
    'http://127.0.0.1:8080/v1',
  ].filter((b): b is string => Boolean(b));
  for (const base of bases) {
    const root = base.replace(/\/v1\/?$/, '').replace(/\/$/, '');
    try {
      const propsRes = await fetch(`${root}/props`, { signal: AbortSignal.timeout(2000) });
      if (!propsRes.ok) continue;
      const props = (await propsRes.json()) as { modalities?: { vision?: boolean }; model_path?: string };
      if (!props?.modalities?.vision) continue;
      // Derive a model id (llama-server accepts any string; prefer the real one).
      let model = 'local';
      try {
        const modelsRes = await fetch(`${root}/v1/models`, { signal: AbortSignal.timeout(2000) });
        if (modelsRes.ok) {
          const m = (await modelsRes.json()) as { models?: { id?: string; name?: string }[]; data?: { id?: string }[] };
          model = m.models?.[0]?.id || m.models?.[0]?.name || m.data?.[0]?.id || model;
        }
      } catch { /* keep 'local' */ }
      process.env.UAP_VISION_ENDPOINT = `${root}/v1`;
      process.env.UAP_VISION_MODEL = model;
      return true;
    } catch {
      /* endpoint unreachable — try the next */
    }
  }
  return false;
}

/** Extract the first JSON object from model output (grammar-free fallback). */
export function parseVisionVerdict(text: string): VisionVerdict | null {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[0]) as { score?: unknown; findings?: unknown };
    const score = Number(parsed.score);
    if (!Number.isFinite(score)) return null;
    const findings = Array.isArray(parsed.findings)
      ? parsed.findings.filter((f): f is string => typeof f === 'string').slice(0, MAX_FINDINGS)
      : [];
    return { score: Math.max(0, Math.min(10, score)), findings };
  } catch {
    return null;
  }
}

/**
 * The project's design system as review context — the DESIGN.md token allow-list
 * (`.uap/design-tokens.json`, generated by `uap design`) plus the DESIGN.md
 * intent prose. Lets the vision reviewer score adherence to the *actual* design
 * system (palette, spacing, fonts, voice) instead of a generic "looks polished"
 * bar. Returns '' when the project has no design system (fail-soft).
 */
export function readDesignContext(projectRoot: string): string {
  const parts: string[] = [];
  try {
    const allowPath = join(projectRoot, '.uap', 'design-tokens.json');
    if (existsSync(allowPath)) {
      const a = JSON.parse(readFileSync(allowPath, 'utf-8')) as {
        name?: string;
        colors?: string[];
        spacing?: string[];
        fontFamilies?: string[];
      };
      if (a.name) parts.push(`Design system: "${a.name}".`);
      if (a.colors?.length) parts.push(`Approved palette (the UI must use ONLY these colours): ${a.colors.slice(0, 14).join(', ')}.`);
      if (a.spacing?.length) parts.push(`Spacing scale: ${a.spacing.slice(0, 12).join(', ')}.`);
      if (a.fontFamilies?.length) parts.push(`Font families: ${a.fontFamilies.slice(0, 4).join(', ')}.`);
    }
  } catch {
    /* allow-list is optional */
  }
  try {
    for (const name of ['DESIGN.md', 'design.md', 'Design.md']) {
      const p = join(projectRoot, name);
      if (existsSync(p)) {
        const md = readFileSync(p, 'utf-8').replace(/^---[\s\S]*?---\s*/, '').trim();
        if (md) parts.push(`Design intent (from ${name}):\n${md.slice(0, 1400)}`);
        break;
      }
    }
  } catch {
    /* DESIGN.md is optional */
  }
  return parts.join('\n');
}

/**
 * Score screenshots against the spec with the configured vision model.
 * `designContext` (see readDesignContext) makes the review judge adherence to
 * the project's design system, not just generic polish. Returns null when
 * unconfigured or on any failure.
 */
export async function judgeScreenshots(
  screenshotPaths: string[],
  spec: string,
  designContext = '',
  fetchImpl?: typeof fetchModelWithRetry
): Promise<VisionVerdict | null> {
  if (!visionJudgeConfigured() || screenshotPaths.length === 0) return null;
  const endpoint = (process.env.UAP_VISION_ENDPOINT as string).replace(/\/$/, '');
  const model = process.env.UAP_VISION_MODEL as string;
  try {
    const images = screenshotPaths.slice(0, MAX_IMAGES).map((p) => ({
      type: 'image_url',
      image_url: { url: `data:image/png;base64,${readFileSync(p).toString('base64')}` },
    }));
    const body = {
      model,
      max_tokens: 800,
      // Disable model "thinking" for this call. A local reasoning model (e.g.
      // Qwen3.6 launched with --reasoning auto) otherwise spends the whole token
      // budget in reasoning_content and returns EMPTY content — the JSON verdict
      // never lands, so the review silently produced nothing. chat_template_kwargs
      // is honored by llama.cpp/vLLM and ignored by cloud OpenAI-compat APIs.
      chat_template_kwargs: { enable_thinking: false },
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text:
                'You are a strict visual reviewer. These are frames of a rendered application. ' +
                'Judge (a) design/aesthetic quality (composition, color, readability, polish), ' +
                '(b) whether the visible behavior matches the spec below, and ' +
                (designContext
                  ? '(c) ADHERENCE TO THE DESIGN SYSTEM below — penalize off-palette colours, off-scale spacing, wrong fonts, and anything that violates the stated design intent. '
                  : '') +
                'Respond with ONLY JSON: ' +
                '{"score": <0-10>, "findings": ["<specific, actionable issue>", ...]}\n\nSPEC:\n' +
                spec.slice(0, 4000) +
                (designContext ? `\n\nDESIGN SYSTEM (score adherence to this):\n${designContext.slice(0, 2500)}` : ''),
            },
            ...images,
          ],
        },
      ],
    };
    const doFetch = fetchImpl ?? fetchModelWithRetry;
    const res = await doFetch(`${endpoint}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(process.env.UAP_VISION_API_KEY ? { Authorization: `Bearer ${process.env.UAP_VISION_API_KEY}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!res.ok) return null;
    const data = (await res.json()) as {
      choices?: Array<{ message?: { content?: string; reasoning_content?: string } }>;
    };
    const msg = data.choices?.[0]?.message;
    // Prefer content; fall back to reasoning_content for any model that still
    // reasons (belt-and-suspenders alongside enable_thinking:false above) — the
    // verdict JSON may be embedded in the reasoning trace.
    return parseVisionVerdict(msg?.content || '') ?? parseVisionVerdict(msg?.reasoning_content || '');
  } catch {
    return null;
  }
}

/** One-line advisory summary for reports/evidence. */
export function visionSummary(verdict: VisionVerdict | null): string | null {
  if (!verdict) return null;
  const findings = verdict.findings.length > 0 ? ` — ${verdict.findings.slice(0, 3).join('; ')}` : '';
  return `vision review: ${verdict.score.toFixed(1)}/10${findings}`;
}
