#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export PROXY_PORT="${PROXY_PORT:-4000}"
export LLAMA_CPP_BASE="${LLAMA_CPP_BASE:-http://127.0.0.1:8080/v1}"
export PROXY_LOG_LEVEL="${PROXY_LOG_LEVEL:-INFO}"

export PROXY_LOOP_BREAKER="${PROXY_LOOP_BREAKER:-on}"
export PROXY_LOOP_WINDOW="${PROXY_LOOP_WINDOW:-6}"
export PROXY_LOOP_REPEAT_THRESHOLD="${PROXY_LOOP_REPEAT_THRESHOLD:-8}"
export PROXY_FORCED_THRESHOLD="${PROXY_FORCED_THRESHOLD:-15}"
export PROXY_NO_PROGRESS_THRESHOLD="${PROXY_NO_PROGRESS_THRESHOLD:-4}"
export PROXY_CONTEXT_RELEASE_THRESHOLD="${PROXY_CONTEXT_RELEASE_THRESHOLD:-0.90}"
export PROXY_GUARDRAIL_RETRY="${PROXY_GUARDRAIL_RETRY:-on}"
export PROXY_SESSION_TTL_SECS="${PROXY_SESSION_TTL_SECS:-7200}"

cd "$ROOT_DIR"
exec python3 tools/agents/scripts/anthropic_proxy.py
