#!/usr/bin/env python3
"""design-token gate: UI edits must stay on the project's DESIGN.md token system.

A Write/Edit/MultiEdit to a UI file (.css/.scss/.tsx/.jsx/.vue/.svelte/.html/...)
whose proposed content introduces a hardcoded color or spacing value NOT present
in the project's design tokens is **blocked**. The agent must use a DESIGN.md
token (or a CSS var), add the value to DESIGN.md (`uap design sync`), or bypass.

The token allow-list is generated by `uap design interrogate|sync` into
`.uap/design-tokens.json` (so this enforcer needs no YAML parser). If that file
is absent, the gate is INACTIVE and fails open — DESIGN.md is opt-in per project.

Mirrors src/design/gate.ts. Escape hatch: UAP_DESIGN_GATE_OFF=1.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import emit, parse_cli, repo_root, worktree_root  # noqa: E402

PATH_WRITE_OPS = {"Write", "Edit", "MultiEdit", "write", "edit", "multiedit"}
UI_EXT = {".css", ".scss", ".sass", ".less", ".tsx", ".jsx", ".vue", ".svelte", ".html", ".astro"}
SPACING_IGNORE = {"0px", "1px", "2px", "3px", "4px"}

HEX_RE = re.compile(r"#[0-9a-fA-F]{3,8}\b")
FUNC_COLOR_RE = re.compile(r"\b(?:rgba?|hsla?|hwb|oklch|oklab|lch|lab)\([^)]*\)", re.IGNORECASE)
PX_RE = re.compile(r"\b\d{1,4}px\b")
VAR_RE = re.compile(r"var\(--[^)]*\)")
# A DESIGN.md token reference is a dotted path in braces (e.g. {colors.primary}).
# Must NOT match CSS declaration blocks like `{color:#fff;}` (they contain
# colons/semicolons), or the scanner would strip whole rules before checking.
REF_RE = re.compile(r"\{[\w.-]+\}")


def _norm_color(c: str) -> str:
    s = c.strip().lower()
    m = re.match(r"^#([0-9a-f])([0-9a-f])([0-9a-f])([0-9a-f])?$", s)
    if m:
        r, g, b, a = m.groups()
        s = f"#{r}{r}{g}{g}{b}{b}{(a + a) if a else ''}"
    return re.sub(r"\s+", "", s)


def _allow_list() -> dict | None:
    for root in (worktree_root(), repo_root()):
        p = root / ".uap" / "design-tokens.json"
        if p.exists():
            try:
                return json.loads(p.read_text())
            except Exception:  # noqa: BLE001
                return None
    return None


def _target_path(args: dict) -> str:
    for key in ("file_path", "path", "notebook_path", "filePath", "target"):
        if args.get(key):
            return str(args[key])
    return ""


def _proposed_content(op: str, args: dict) -> str:
    # Write: full content. Edit: the inserted text. MultiEdit: all inserts.
    if args.get("content"):
        return str(args["content"])
    if args.get("new_string"):
        return str(args["new_string"])
    edits = args.get("edits")
    if isinstance(edits, list):
        return "\n".join(str(e.get("new_string", "")) for e in edits if isinstance(e, dict))
    return ""


def _scan(content: str, allow: dict) -> tuple[list[str], list[str]]:
    allow_colors = {_norm_color(c) for c in allow.get("colors", [])}
    allow_spacing = set(allow.get("spacing", [])) | set(allow.get("radii", [])) | set(allow.get("fontSizes", []))
    off_colors: list[str] = []
    off_spacing: list[str] = []

    for raw in content.split("\n"):
        t = raw.strip()
        if t.startswith("//") or t.startswith("*") or t.startswith("/*"):
            continue
        line = REF_RE.sub("", VAR_RE.sub("", raw))
        for m in HEX_RE.finditer(line):
            if _norm_color(m.group(0)) not in allow_colors:
                off_colors.append(m.group(0))
        for m in FUNC_COLOR_RE.finditer(line):
            if re.sub(r"\s+", "", m.group(0).lower()) not in allow_colors:
                off_colors.append(m.group(0))
        for m in PX_RE.finditer(line):
            px = m.group(0)
            if px not in SPACING_IGNORE and px not in allow_spacing:
                off_spacing.append(px)

    return off_colors, off_spacing


def main() -> None:
    op, args = parse_cli()

    if os.environ.get("UAP_DESIGN_GATE_OFF") == "1":
        emit(True, "UAP_DESIGN_GATE_OFF override set")
    if op not in PATH_WRITE_OPS:
        emit(True, "not a file-write operation")

    target = _target_path(args)
    if Path(target).suffix.lower() not in UI_EXT:
        emit(True, "not a UI file")

    allow = _allow_list()
    if not allow:
        emit(True, "no DESIGN.md token allow-list (.uap/design-tokens.json) — gate inactive")

    content = _proposed_content(op, args)
    if not content:
        emit(True, "no proposed content to scan")

    off_colors, off_spacing = _scan(content, allow)
    if not off_colors and not off_spacing:
        emit(True, "on-token UI edit")

    name = allow.get("name", "DESIGN.md")
    palette = ", ".join(allow.get("colors", [])[:5])
    spacing_scale = ", ".join(allow.get("spacing", []))
    lines = [f'design-token gate: this UI edit introduces values not in the "{name}" design system.']
    if off_colors:
        uniq = list(dict.fromkeys(off_colors))[:6]
        lines.append(f"  off-token colors: {', '.join(uniq)}")
        lines.append(f"  → use a DESIGN.md color token ({palette}{', …' if len(allow.get('colors', [])) > 5 else ''}) or a CSS var.")
    if off_spacing:
        uniq = list(dict.fromkeys(off_spacing))[:6]
        lines.append(f"  off-scale spacing: {', '.join(uniq)}")
        lines.append(f"  → use a spacing token ({spacing_scale or 'define spacing in DESIGN.md'}).")
    lines.append("  Add the value to DESIGN.md (then `uap design sync`), reference a token, or bypass with UAP_DESIGN_GATE_OFF=1.")
    emit(False, "\n".join(lines))


if __name__ == "__main__":
    main()
